---
- name: Install minimal required packages
  become: true
  ansible.builtin.apt:
    update_cache: true
    pkg:
      - git
      - gpg
      - nano
      - rclone
      - zsh

- name: Download oh-my-zsh latest installer
  ansible.builtin.get_url:
    url: https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh
    dest: /tmp/omz_install.sh
    mode: 0770
  register: omz_installer

- name: Install oh-my-zsh
  ansible.builtin.shell: "{{ omz_installer.dest }} --unattended --keep-zshrc"
  register: omz_install_result
  changed_when: "omz_install_result.rc == 0"
  ignore_errors: yes
  failed_when: false
  
- name: Git checkout powerlevel10k
  ansible.builtin.git:
    repo: 'https://github.com/romkatv/powerlevel10k'
    dest: "{{ ansible_env.HOME }}/.oh-my-zsh/themes/powerlevel10k"
    depth: 1
    update: yes

- name: Git checkout zsh-autosuggestions
  ansible.builtin.git:
    repo: 'https://github.com/zsh-users/zsh-autosuggestions'
    dest: "{{ ansible_env.HOME }}/.oh-my-zsh/plugins/zsh-autosuggestions"
    depth: 1
    update: yes

- name: Git checkout zsh-completions
  ansible.builtin.git:
    repo: 'https://github.com/zsh-users/zsh-completions'
    dest: "{{ ansible_env.HOME }}/.oh-my-zsh/plugins/zsh-completions"
    depth: 1
    update: yes

- name: Git checkout zsh-syntax-highlighting
  ansible.builtin.git:
    repo: 'https://github.com/zsh-users/zsh-syntax-highlighting'
    dest: "{{ ansible_env.HOME }}/.oh-my-zsh/plugins/zsh-syntax-highlighting"
    depth: 1
    update: yes

- name: Change user shell to zsh 
  become: true
  ansible.builtin.shell: "chsh -s $(which zsh) {{ ansible_env.USER }}"
  changed_when: false

- name: Copy dotfiles
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ ansible_env.HOME }}/{{ item }}"
    mode: 0660
  with_items:
    - .gitconfig
    - .nanorc
    - .p10k.zsh
    - .zshrc
